### ISSUE TITLE
When using antq as a lein plugin it does not seem to find outdated deps in github actions

### ISSUE THREAD

**Issue by lread** [liquidz/antq#274]
Hello @liquidz! I just noticed a thing while helping out with [cheshire](https://github.com/dakrone/cheshire/pull/229).

## Problem

When using antq as a lein plugin, it finds outdated deps in `project.clj` but does not seem to find them in github actions config.

## Minimal Scenario
Here's a wee repro, from an empty dir:

`project.clj`
```clojure
(defproject foo "1.2.3-SNAPSHOT"
  :description "Testing antq as lein plugin"
  :dependencies [[rewrite-clj/rewrite-clj "0.6.8"]]
  :plugins [[com.github.liquidz/antq "2.11.1276"]])
```

`.github/workflows/test.yml`
```yaml
name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 23

    - name: Install Clojure Tools
      uses: DeLaGuardo/setup-clojure@13.1
      with:
        lein: 'latest'
```

## Actual Behaviour

When I run antq as a lein plugin, I only see outdated deps for `project.clj`:

```shell
$ lein antq
[##################################################] 4/4
| :file       | :name                   | :current | :latest |
|-------------|-------------------------|----------|---------|
| project.clj | nrepl/nrepl             | 1.0.0    | 1.3.1   |
|             | rewrite-clj/rewrite-clj | 0.6.8    | 1.1.49  |

Available changes:
- https://github.com/nrepl/nrepl/blob/v1.3.1/CHANGELOG.md
``` 

## Expected Behaviour
I would expect to see outdated deps for all supported files.
For example, when I run antq from clojure in the same dir, I see all outdated deps (including those for github actions):

```shell
$ clojure -Sdeps '{:deps {com.github.liquidz/antq {:mvn/version "2.11.1276"}}}' -M -m antq.core
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[##################################################] 5/5
| :file                      | :name                    | :current | :latest |
|----------------------------|--------------------------|----------|---------|
| .github/workflows/test.yml | DeLaGuardo/setup-clojure | 13.1     | 13.2    |
|                            | actions/checkout         | v3       | v4.2.2  |
| project.clj                | rewrite-clj/rewrite-clj  | 0.6.8    | 1.1.49  |

Available changes:
- https://github.com/DeLaGuardo/setup-clojure/compare/13.1...13.2
- https://github.com/actions/checkout/blob/v4.2.2/CHANGELOG.md
```

Does that make sense?
