### ISSUE TITLE
Upgrade does not work for github actions for some valid yaml indentations

### ISSUE THREAD

**Issue by lread** [liquidz/antq#277]
## Setup

Given this valid `.github/workflows/test1.yml`:
```yaml
name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 23

    - name: Install Clojure Tools
      uses: DeLaGuardo/setup-clojure@13.1
      with:
        lein: 'latest'
```

Setup for comparison
```
git init
git add .github
```

## Repro
If I run: 
```
clojure -Sdeps '{:deps {com.github.liquidz/antq {:mvn/version "2.11.1276"}}}' -M -m antq.core --upgrade --force
```

At the time of this writing, we see the following output:
```
[##################################################] 3/3
| :file                       | :name                    | :current | :latest |
|-----------------------------|--------------------------|----------|---------|
| .github/workflows/test1.yml | DeLaGuardo/setup-clojure | 13.1     | 13.2    |
|                             | actions/checkout         | v3       | v4.2.2  |

Available changes:
- https://github.com/DeLaGuardo/setup-clojure/compare/13.1...13.2
- https://github.com/actions/checkout/blob/v4.2.2/CHANGELOG.md
Upgraded actions/checkout 'v3' to 'v4' in .github/workflows/test1.yml.
Upgraded DeLaGuardo/setup-clojure '13.1' to '13.2' in .github/workflows/test1.yml.
```
Which seems good, but if I run `git diff`

## Expected Behaviour
I would expect git diff to show the changes antq applied.

## Actual Behaviour
Git diff shows that no changes have been applied.

## Diagnosis
If we replace `.github/workflows/test1.yml` with a slightly different indentation:

```yaml
name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 23

      - name: Install Clojure Tools
        uses: DeLaGuardo/setup-clojure@13.1
        with:
          lein: 'latest'
```

And then run `git add .github` to prepare for our diff later.

And then rerun antq as above, we get the same output.

But now, if we git diff we see what we'd expect:
```diff
diff --git a/.github/workflows/test1.yml b/.github/workflows/test1.yml
index d2717b5..987624f 100644
--- a/.github/workflows/test1.yml
+++ b/.github/workflows/test1.yml
@@ -14,7 +14,7 @@ jobs:
 
     steps:
       - name: Checkout
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
       - name: Setup Java
         uses: actions/setup-java@v4
@@ -23,6 +23,6 @@ jobs:
           java-version: 23
 
       - name: Install Clojure Tools
-        uses: DeLaGuardo/setup-clojure@13.1
+        uses: DeLaGuardo/setup-clojure@13.2
         with:
           lein: 'latest'

```

## To question
Is the yaml I tested with valid?
Yes, I think so. I've happened to use this indentation on other projects I help to maintain, [for example etaoin](https://github.com/clj-commons/etaoin/blob/7b7efc60ce3d928e1d11e7fb2dde5eeb1845686e/.github/workflows/test.yml#L20-L57).

## Next Steps
I'd be happy to take a peek and work on a fix if that is interesting to you.
