### ISSUE TITLE
Github actions: "latest" dependency version label causes false positive

### ISSUE THREAD

**Issue by pmonks** [liquidz/antq#67]
In my `.github/workflows/build.yml` I have the following:

```yaml
# ...
jobs:
  build:
# ...
    steps:
# ...
      - name: Install Clojure CLI
        uses: DeLaGuardo/setup-clojure@3.1
        with:
          tools-deps: latest
# ...
```

This causes antq v0.12.0 to emit the following false positive:

```
| .github/workflows/build.yml | clojure/brew-install |               latest |                      1.10.3.814 |
```
